# Generated by Django 2.2 on 2019-04-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joinsquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('gamername', models.CharField(max_length=25)),
                ('playerid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('photo', models.TextField()),
                ('level', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('gamername', models.CharField(max_length=25)),
                ('player_profile', models.TextField()),
            ],
        ),
    ]
