# Generated by Django 2.1.7 on 2019-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='player_photo')),
                ('level', models.IntegerField(default='1233456')),
                ('player_id', models.IntegerField(default='1233456')),
                ('gamername', models.CharField(default='1233456', max_length=25)),
                ('player_profile', models.ImageField(upload_to='player_profile')),
            ],
        ),
    ]
