# Generated by Django 2.1.7 on 2019-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='gamername',
            field=models.CharField(default='123345', max_length=25),
        ),
    ]
