# Generated by Django 2.1.7 on 2019-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190413_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='gamername',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
