# Generated by Django 2.2 on 2019-04-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190413_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='age',
        ),
    ]
